### ISSUE TITLE
style attribute url value error

### ISSUE THREAD

**Issue by kodal** [pug-php/pug-symfony#11]
`.slide(style="background-image: url(" + image + ");")`
rendered like
`<div class="slide" style="background-image:$view[route]->url(image.jpg);"></div>`
I tried css_url, but error:
`undefined variable: css_url`

P.S. pug-symfony: 2.2.1

**Comment by kylekatarnls** [comment]
Hi, I confirm this regression due to the last helpers feature added I think. I work on it.

**Comment by kylekatarnls** [comment]
Hi, you can `composer update` to solve the problem.
