### ISSUE TITLE
Add entity private properties access

### ISSUE THREAD

**Issue by khlevnov** [pug-php/pug-symfony#2]
Hello! Thank you for you good bundle, but i have small problem.
In twig templates I can get access to doctrine entites without using entity methods, like article.title (not article.getTitle()). It is a very useful feature, because I can use the same pug templates in two environments -- with gulp and with symfony.
http://twig.sensiolabs.org/doc/templates.html#variables
Will you add this feature in pug-symfony in future?

**Comment by kylekatarnls** [comment]
Hi, good point!

It could be an option/feature directly in Pug because the same need exists in others frameworks. A quick fix you can use for the moment is to edit in **vendor/pug-php/pug/src/Jade/Compiler/CompilerFacade.php** the method **getPropertyFromAnything**:

`````` php
    /**
     * Get property from object or entry from array.
     *
     * @param $anything object|array
     * @param $key mixed key to retrive from the object or the array
     *
     * @return mixed
     */
    public static function getPropertyFromAnything($anything, $key)
    {
        $value = null;

        if (is_array($anything)) {
            $value = isset($anything[$key]) ? $anything[$key] : null;
        }

        if (is_object($anything)) {
            $method = 'get' . ucfirst($key);
            $value = isset($anything->$key) ? $anything->$key : (method_exists($anything, $method)
                ? $anything->$method()
                : null
            );
        }

        return $value;
    }```
``````

**Comment by khlevnov** [comment]
Thanks you for fix! An small another question:
Will you php objects methods from pug templates?

**Comment by kylekatarnls** [comment]
Just have to ask: https://github.com/pug-php/pug/releases/tag/2.0.4

Enter: `composer update` to upgrade pug-php and you will be able to use getters:

``` pug
article
  h2=article.title
  p=article.content
```

Please let me know if all works for you in your templates.

**Comment by khlevnov** [comment]
Thanks for your upgrade! All right, access to private properties works correctly.

I translated pug-symfony readme with my small notes in Russian, you can see it here http://khlevnov.ru/articles/how-to-use-pug-in-symfony.
Template for this article was written in Pug ;)

**Comment by kylekatarnls** [comment]
Hi,

Thanks a lot for this article. Just a note, I would not recommand to use the dev-master branch. Prefer use a minimum-stability to stable and the last stable release with something like:
`composer require pug-php/pug-symfony ">=2.0.0"`
