### ISSUE TITLE
Array parameters in hellpers

### ISSUE THREAD

**Issue by NotJustPizza** [pug-php/pug-symfony#5]
I want to use path() with second parameter (associative array).

Twig Code (works):
```
{{ path('web.index', {'_locale': 'en'}) }}
```

Pug Code (doesn't work, but with path('web.index') works):
```
a(href=path('web.index', {_locale: 'en'}))
```
Error:
```
Parse error: syntax error, unexpected '{'
500 Internal Server Error - FatalThrowableError 
```

**Comment by kylekatarnls** [comment]
Hey, you can use `'languageExpression' => 'js'` as an option to handle JS expression with **js-phpize** (a better tool that will be native in the next major version: see https://github.com/phug for more details), else you can use PHP syntax:
```pug
a(href=path('web.index', ['_locale' => 'en']))
```

**Comment by NotJustPizza** [comment]
PHP syntax works, thank you!
