### ISSUE TITLE
extends can find files, but include can't

### ISSUE THREAD

**Issue by Evertt** [pug-php/pug-symfony#52]
At the top of my `home.pug` I have:

```pug
extends _layout
include mixins/_global-mixins
include mixins/_project-mixins
include mixins/_project-vars
```

It can find `_layout.pug`, but it can't find `mixins/_gobal-mixins.pug`. After some debugging on my part it seems like `include` is using twig functions, but `extends` isn't. Maybe that's why? Because Twig doesn't know how to find a pug-file without the extension after it?

**Comment by kylekatarnls** [comment]
Hello, what is your version of pug-php/pug-symfony (include only use Twig since 3.0.0), what is your files structure?

Please also dump the full error which contains a stack trace and the list of paths that are used for the include.

**Comment by Evertt** [comment]
@kylekatarnls sorry I already moved on to just manually converting my pug files to twig, because I was in a hurry. And right now I don't have the time to tackle this thing. 😅
